Configuración de guardado
Se cambió el formato de salida del archivo:
> st_write(MFE,
+          dsn = "outputs/MFE.shp",
+          delete_dsn = TRUE)
Deleting source `outputs/MFE.shp' failed
Writing layer `MFE' to data source `outputs/MFE.shp' using driver `ESRI Shapefile'
Writing 1392101 features with 16 fields and geometry type Unknown (any).
Failed to create feature 897482 in MFE
Error: Feature creation failed.
Además: Avisos:
1: In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Error 1: outputs/MFE.shp does not appear to be a file or directory.
2: In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Message 1: 2GB file size limit reached for outputs\MFE.shp. Going on, but might cause compatibility issues with third party software
3: In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  :
  GDAL Error 1: Failed to write shape object. The maximum file size of 4294964736 has been reached. The current record of size 5336 cannot be added.